### ISSUE TITLE
JS Engine: Known Issues

### ISSUE THREAD

**Issue by JordanSantiagoYT** [JordanSantiagoYT/FNF-JS-Engine-Rewrite#1]
this is just a page for those that want to know what issues i'm aware of

## Status Legend
✅ - Fixed & Released
❌ - Not fixed yet
🟢 - Fixed, will release in the next update
🟡 - Working on a fix
🟠 - Low Priority
🔴 - Currently not a priority
⚫ - Unfixable/Unable to implement
❓ - Could possibly just be a bug on my end unless someone else reports it

# Bugs

Big icons will crop off - ❌🟡
Sometimes the preloader will crash the engine because of a broken path - ❌🟡
If you exit an editor while music is fading in, the engine will crash - 🟢
If you reload a JSON in the Chart Editor, the music will stack on top of each other - 🟢
macOS users cannot open the Engine - ❌🔴 (I do not use macOS.)
Linux users will have frames saved in Rendering Mode save to the main directory instead - 🟢
If GPU Caching is enabled, Get Icon Color is broken and always returns a black color - 🟢

# Suggestions
Extra key support (up to 18K) - ⚫ (Would break noteskins.)
Modchart Editor - ❌🔴
Making the engine work with the latest libraries - ✅

**Comment by TofpFL** [comment]
❌🟢? wtf?

**Comment by moxie-coder** [comment]
> ❌🟢? wtf?

did you not read?

**Comment by TofpFL** [comment]
> > ❌🟢? wtf?
> 
> did you not read?

Just put the green circle in there. No need for a red X 💀

**Comment by Unbroke50** [comment]
> > > ❌🟢? wtf?
> > 
> > 
> > did you not read?
> 
> Just put the green circle in there. No need for a red X 💀

lol yea
