### ISSUE TITLE
my pc shows this when i am trying to enter any song

### ISSUE THREAD

**Issue by Helly1645** [JordanSantiagoYT/FNF-JS-Engine-Rewrite#4]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

my pc shows this when i am trying to enter any song and then crashes
![2024-10-04_17-27-56](https://github.com/user-attachments/assets/7f7e0411-5faf-4130-bbee-f74e23b52026)
i don't know why is that, but it started from v32 or v33 i don't remember and it is still here on v35! Pls fix

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Enter ANY song (even tutorial works) in freeplay
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No only put few folders and a zipfile in mods

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
you reported this in the rewrite repo, not the main repo
